### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by eelke** [knownasilya/google-maps-drawing-tools#3]
Visiting https://ilyaradchenko.com/google-maps-drawing-tools/ yields a blank page. 
In the network inspector I noticed while trying to load the page's content as JSON, the server is returning an html-file. https://ilyaradchenko.com/content/google-maps-drawing-tools.json

**Comment by knownasilya** [comment]
Thanks, will look to resolve

**Comment by knownasilya** [comment]
Fixed, use the new url https://google-maps-drawing-tools.netlify.app/
